server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events_database
    username: root
    password: Chitra@234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: gtdfhfhfdghdfhtdthdfhtfyhjfyfyjgfyffyfjgjgtyugughij
  expiration: 86400000 # 24 hours in milliseconds

#logging:
#  level:
#    root: DEBUG


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE